hortonworks-spark/spark-llap

src/main/scala/org/apache/spark/sql/hive/llap/LlapExternalCatalog.scala
This PR delegates `DROP TABLE` to Hive to use proper authorization.
This closes #10 .
=> [SPARK-LLAP-10] `DROP TABLE` should be blocked properly according to the access rule

src/main/scala/com/hortonworks/spark/sql/hive/llap/HS2JDBCWrapper.scala
Current, SPARK-LLAP fails to drop tables with `double` columns.
```sql
$ bin/beeline -u jdbc:hive2://localhost:10016 -n hive -p password -e 'drop table salary'
Connecting to jdbc:hive2://localhost:10016
...
Error: org.apache.spark.sql.catalyst.parser.ParseException:
extraneous input 'PRECISION' expecting {<EOF>, '('}(line 1, pos 7)
== SQL ==
DOUBLE PRECISION
-------^^^ (state=,code=0)
Closing: 0: jdbc:hive2://localhost:10016
```
The root cause is that `JDBCWrapper` returns `DOUBLE PRECISION` instead of `DOUBLE`.
This closes #13 .
=> [SPARK-LLAP-13] `DROP TABLE` fails on tables with `double` columns

src/main/scala/org/apache/spark/sql/hive/llap/LlapExternalCatalog.scala
Currently, `SHOW TABLE 't*'` shows all tables. In other words, the pattern is ignored.
Manual.
This closes #19.
=> [SPARK-LLAP-19] SHOW TABLE should support pattern filtering

src/main/scala/org/apache/spark/sql/hive/llap/LlapExternalCatalog.scala, src/main/scala/org/apache/spark/sql/hive/llap/LlapSessionCatalog.scala
This PR handles the following ALTER TABLE statements correctly.
* ALTER TABLE ... RENAME TO
* ALTER TABLE ... SET TBLPROPERTIES
* ALTER TABLE ... UNSET TBLPROPERTIES
* ALTER TABLE ... ADD PARTITION
* ALTER TABLE ... DROP PARTITION
* ALTER TABLE ... PARTITION ... RENAME TO PARTITION
* ALTER TABLE ... PARTITION SET LOCATION
* ALTER TABLE ... RECOVER PARTITIONS
Manual.
This closes #21 and #22.
=> [SPARK-LLAP-21] ALTER TABLE should be handled correctly

patch/0001-SPARK-LLAP-RANGER-Integration.patch
SPARK-LLAP needs Apache Spark patch. This PR adds the patch file for Apache Spark `branch-2.1`.
**BUILD**
```bash
git clone https://github.com/apache/spark.git -b branch-2.1
cd spark
curl https://raw.githubusercontent.com/hortonworks-spark/spark-llap/SPARK-LLAP-27/patch/0001-SPARK-LLAP-RANGER-Integration.patch | git am
build/sbt -Pyarn -Phadoop-2.7 -Phive -Phive-thriftserver package
```
**RUN SPARK THRIFT SERVER**
```bash
sbin/start-thriftserver.sh --conf spark.sql.hive.llap=true
```
**TEST**
```bash
cd src/test/python
./spark-ranger-test.py
......................
Ran 22 tests in 2900.331s
OK
```
This closes #27 and #8 .
=> [SPARK-LLAP-27] Add Apache Spark 2.1 Patch

src/test/resources/answer/desc_t_alter.err_answer, src/test/resources/answer/desc_t_create.err_answer, src/test/resources/answer/desc_t_drop.err_answer, src/test/resources/answer/desc_t_index.err_answer, src/test/resources/answer/desc_t_lock.err_answer, src/test/resources/answer/desc_t_no.err_answer, src/test/resources/answer/desc_t_partial.err_answer, src/test/resources/answer/desc_t_update.err_answer
Since RANGER-1195, Apache Ranger gives more accurate error message for `DESC` statements. We should update the answer files.
```bash
$ ./spark-ranger-test.py TableTestSuite.test_10_desc
.
Ran 1 test in 52.666s
OK
```
=> [SPARK-LLAP-36] Update answer files according to RANGER-1195

src/test/python/spark-ranger-secure-test.py
This PR adds a test suite for secure cluster using Kerberos. Basically, the test coverage is the same.
```bash
$ cd src/test/python
$ ./spark-ranger-secure-test.py
.......................
Ran 23 tests in 2509.880s
OK
```
This closes #39
=> [SPARK-LLAP-38] Add a test suite for secure cluster

src/main/scala/org/apache/spark/sql/hive/llap/LlapExternalCatalog.scala, src/test/resources/answer/drop_db_2_db_no.err_answer, src/test/resources/answer/drop_db_cascade_3_db_no.err_answer
This PR implements the followings.
- Database existence check should not access HDFS directly.
- `SHOW DATABASES` should show the accessible databases.
- Re-add the `getTable` though JDBC feature to support fallback operation in case of direct access failure.
Pass the test.
This closes #40 .
=> [SPARK-LLAP-40] Database existence check should be handled correctly.

README.md, examples/src/main/python/spark_llap_dsl.py, examples/src/main/python/spark_llap_sql.py
This PR adds python examples to show how to use `spark-submit`.
bin/spark-submit --jars spark-llap_2.11-1.0.X-2.1.jar spark_llap_sql.py
bin/spark-submit --jars spark-llap_2.11-1.0.X-2.1.jar spark_llap_dsl.py
This closes #42.
=> [SPARK-LLAP-42] Add Python Examples

build.sbt
This PR bumps the version to 1.0.4-2.1 and support `publish`.
```
$ ./build/sbt publish -Drepourl=... -Duser=... -Dpassword=...
...
```
This closes #45 .
=> [SPARK-LLAP-45] Bump to 1.0.4-2.1 and support `publish`

README.md
Apache Ranger becomes TLP now.
https://blogs.apache.org/foundation/entry/the-apache-software-foundation-announces3
N/A
This closes #50.
=> [SPARK-LLAP-50] Remove `incubating` from Apache Ranger

build.sbt
To publish `pom.xml`, we should not use `excludeAll`.
```
$ build/sbt publish-local
[info] Loading project definition from /Users/dhyun/spark-llap/project
[info] Set current project to spark-llap (in build file:/Users/dhyun/spark-llap/)
[info] Packaging /Users/dhyun/spark-llap/target/scala-2.11/spark-llap_2.11-1.0.4-2.1-sources.jar ...
[info] Done packaging.
[info] Main Scala API documentation to /Users/dhyun/spark-llap/target/scala-2.11/api...
[warn] Skipped generating '<exclusion/>' for javax.servlet#*. Dependency exclusion should have both 'org' and 'module' to comply with Maven POM's schema.
[warn] Skipped generating '<exclusion/>' for javax.servlet.jsp#*. Dependency exclusion should have both 'org' and 'module' to comply with Maven POM's schema.
[warn] Skipped generating …
```
=> [SPARK-LLAP-52] Dependency exclusion should have both 'org' and 'module'

build.sbt
Up to now, `spark-llap` can be used with `--jars`, but fails on `--packages`.
This PR aims to support `--packages` by cleaning up the dependencies.
```
$ spark-shell --packages com.hortonworks:spark-llap_2-11:1.0.2-2.1 --repositories http://repo.hortonworks.com/content/groups/public
scala> sql("show tables").show
17/01/31 00:31:38 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.RuntimeException: Stream '/jars/org.apache.curator_apache-curator-2.7.1.jar' was not found.
```
After publishing to Maven, use `--packages` option.
=> [SPARK-LLAP-48] Support `--packages`

build.sbt
This PR changes `groupId` from `com.hortonworks` into `com.hortonworks.spark`. Accordingly, this bump the version into `1.0.6`.
**BEFORE**
```xml
<groupId>com.hortonworks</groupId>
<artifactId>spark-llap_2.11</artifactId>
```
**AFTER**
```xml
<groupId>com.hortonworks.spark</groupId>
<artifactId>spark-llap_2.11</artifactId>
```
N/A
=> [SPARK-LLAP-59] Use `com.hortonworks.spark` instead of `com.hortonworks`

build.sbt
`SPARK-LLAP-59` accidentally *reverts* the code of `SPARK-LLAP-53`. This broke `--packages` support in `spark-shell`. This PR recovers that.
```
// Make assembly as default artifact
...
```
Manual.
```
SPARK_MAJOR_VERSION=2 spark-shell --packages com.hortonworks.spark:spark-llap_2.11:1.0.7-2.1 --repositories ... --conf spark.sql.hive.llap=true
```
This closes #62 .
=> [SPARK-LLAP-62] Recover the change on default jar at SPARK-LLAP-59

build.sbt
Currently, spark-llap includes `netty-all` from Apache Hadoop which has different versions from Apache Spark. This PR overrides netty-all depenency to be consist with Apache Spark and also shades that.
Tested manually in the secure cluster and passed the following non-kerberized Ranger suite additionally.
```
[hive@hdp26-6 python]$ ./spark-ranger-test.py DbTestSuite
....
Ran 4 tests in 323.545s
OK
[hive@hdp26-6 python]$ ./spark-ranger-test.py TableTestSuite
...................
Ran 19 tests in 1843.179s
OK
```
This closes #104
=> [SPARK-LLAP-104] Override and shade netty-all dependency

src/main/scala/com/hortonworks/spark/sql/hive/llap/LlapRelation.scala, src/main/scala/org/apache/spark/sql/hive/llap/DefaultSource.scala
I start and close the connection when it is used in the llap relation. 
=> [Bug-64676] Should close/reuse connections in spark-llap

src/main/scala/org/apache/spark/sql/hive/llap/LlapContext.scala
I modify the LlapCatalog to enforce the access control under list tables. 
I test this manually on a security cluster based on spark 1.6.
=> [SPARK-LLAP-127] Table information will under access control

src/test/resources/answer/create_location_2_t_alter.err_answer, src/test/resources/answer/create_location_2_t_create.err_answer, src/test/resources/answer/create_location_2_t_drop.err_answer, src/test/resources/answer/create_location_2_t_full.err_answer, src/test/resources/answer/create_location_2_t_index.err_answer, src/test/resources/answer/create_location_2_t_lock.err_answer, src/test/resources/answer/create_location_2_t_no.err_answer, src/test/resources/answer/create_location_2_t_partial.err_answer, src/test/resources/answer/create_location_2_t_select.err_answer, src/test/resources/answer/create_location_2_t_update.err_answer
This PR updates the test answer files for `test_22_create_location`.
**BEFORE**
```bash
$ python spark-ranger-secure-test.py
........F...............
Ran 24 tests in 3165.302s
```
**AFTER**
```bash
$ python spark-ranger-secure-test.py TableTestSuite.test_22_create_location
.
Ran 1 test in 178.611s
OK
```
Pass the test suite.
=> [SPARK-LLAP-129][TEST][FOLLOW-UP] Update Ranger error message.

src/test/resources/answer/create_location_2_t_alter.err_answer, src/test/resources/answer/create_location_2_t_create.err_answer, src/test/resources/answer/create_location_2_t_drop.err_answer, src/test/resources/answer/create_location_2_t_full.err_answer, src/test/resources/answer/create_location_2_t_index.err_answer, src/test/resources/answer/create_location_2_t_lock.err_answer, src/test/resources/answer/create_location_2_t_no.err_answer, src/test/resources/answer/create_location_2_t_partial.err_answer, src/test/resources/answer/create_location_2_t_select.err_answer, src/test/resources/answer/create_location_2_t_update.err_answer, src/test/resources/policies/5_hdfs.json
In HDP 2.6.1, there are two differences.
- `hdfs://tmp` is not allowed by default. We need HDFS plugin policy.
- INSERT INTO / CREATE TABLE / CREATE TABLE with LOCATION error messages are changed.
```
[hive@hdp26-6 python]$ python spark-ranger-secure-test.py TableTestSuite.test_21_create_as
.
Ran 1 test in 204.527s
OK
[hive@hdp26-6 python]$ python spark-ranger-secure-test.py TableTestSuite.test_22_create_location
.
Ran 1 test in 187.236s
OK
[hive@hdp26-6 python]$ python spark-ranger-secure-test.py TableTestSuite.test_70_insert
.
Ran 1 test in 157.783s
OK
```
This closes #137 .
=> [SPARK-LLAP-137][TEST] Add Ranger HDFS policy and update error messages

build.sbt, src/main/scala/com/hortonworks/spark/sql/hive/llap/HS2JDBCWrapper.scala, src/main/scala/com/hortonworks/spark/sql/hive/llap/RowConverter.scala, src/main/scala/org/apache/spark/sql/hive/llap/LlapExternalCatalog.scala
This bumps the Hive dependency to HDP 2.6.1.0 for Spark-LLAP master/branch-2.1.
```
[hive@hdp26-6 python]$ python spark-ranger-secure-test.py
........................
Ran 24 tests in 3723.090s
OK
```
This closes #135 .
=> [SPARK-LLAP-135] Bump to HDP 2.6.1.

build.sbt
1. change some artifact from compile to provided
2. exclude the hadoop common, hdfs etc from hive
3. remove the force for the spark
4. exclude: commons-beanutils etc
test based on the spark-range-security test script. 
For the generated package, its size is reduced from 105139716  to 60628114. 
```
....
Ran 4 tests in 367.168s
OK
....................
Ran 20 tests in 2308.878s
OK
```
=> [SPARK-LLAP-125] Reduce the number of included artifacts in the assembly jar

src/main/scala/com/hortonworks/spark/sql/hive/llap/LlapRelation.scala
This improves performance of count(*) queries since we were previously selecting all columns of the table.
=> Push down count(*) query to Hive when requiredColumns is an empty list.

src/main/scala/org/apache/spark/sql/hive/llap/LlapContext.scala
Add the access control for describe database.table
**BEFORE**
```
0: jdbc:hive2://ctr-e133-1493418528701-160107> desc spark_ranger_test.t_no;
+-----------+------------+----------+--+
| col_name  | data_type  | comment  |
+-----------+------------+----------+--+
+-----------+------------+----------+--+
No rows selected (0.782 seconds)
0: jdbc:hive2://ctr-e133-1493418528701-160107> desc spark_ranger_test.t_full;
+-----------+------------+----------+--+
| col_name  | data_type  | comment  |
+-----------+------------+----------+--+
| a         | int        |          |
| b         | int        |          |
+-----------+------------+----------+--+
```
**AFTER**
```
0: jdbc:hive2://ctr-e133-1493418528701-160107> desc spark_ranger_test.t_no;
Error: …
```
=> [SPARK-LLAP-133][BRANCH-1.6] Access control for DESC TABLE

src/main/scala/org/apache/spark/sql/hive/llap/LlapExternalCatalog.scala
This PR uses `CREATE EXTERNAL TABLE` instead of `CREATE TABLE` to avoid accidental dropping or chaning the existing location. This might happen in some cases.
This closes #157 .
Pass the test suite. I tested this in HDP 2.6.1.0.
```
[hive@hdp26-6 python]$ ./spark-ranger-secure-test.py
.........................
Ran 25 tests in 3670.599s
OK
```
=> [SPARK-LLAP-157] Use CREATE EXTERNAL TABLE to check permission

src/main/scala/com/hortonworks/spark/sql/hive/llap/LlapRelation.scala, src/main/scala/org/apache/spark/sql/hive/llap/LlapMetastoreCatalog.scala
This PR supports `sizeInBytes()` in LlapRelation.
Pass the test suite. It's tested on HDP 2.6.1.0.
```
$ python spark-ranger-secure-test.py
.........................
Ran 25 tests in 3706.998s
OK
```
=> [SPARK-LLAP-156] Support LlapRelation table size.

.travis.yml
Since Spark 2.2 removes Remove Java 7 support, this PR removes JDK7 from Travis CI, too.
Pass the Travis CI with only JDK8. This is irrelevant to test suite.
This closes #166 .
=> [SPARK-LLAP-166] Remove JDK7 from Travis CI

src/main/scala/org/apache/spark/sql/hive/llap/DefaultSource.scala, src/main/scala/org/apache/spark/sql/hive/llap/LlapExternalCatalog.scala, src/main/scala/org/apache/spark/sql/hive/llap/LlapSessionCatalog.scala
This bug is brought from commit: 5b5ea71ecbede891fe4ca2427cfb7ef6c65958c7
update the getUser method name for matching the provided function name of Spark Internal side. 
The reason why it passed the test suite at that time.
(1) The reason is the mismatch between PR 5b5ea71ecbede891fe4ca2427cfb7ef6c65958c7  and test env setup. The PR do not synchronized on time. 
Are you sure whether the test result reported in the PR is correct with this patch?
(2) This PR is already in branch branch-2.2-HDP-2.6.2.0, and test via provided security test script and deployed to the QE team testing environment. It already passed the test as well. 
unit test passed. 
```
[root@ctr-e134-1499953498516-70977-01-000007 python]# ./spark-ranger-secure-test.py TableTestSuite
..................... …
```
=> [SPARK-LLAP-171] Fix a function name typo at SparkSessionState.getUserNameString

build.sbt, src/main/scala/com/hortonworks/spark/sql/hive/llap/HS2JDBCWrapper.scala, src/main/scala/com/hortonworks/spark/sql/hive/llap/LlapRelation.scala, src/main/scala/org/apache/spark/sql/hive/llap/DefaultSource.scala, src/main/scala/org/apache/spark/sql/hive/llap/LlapExternalCatalog.scala, src/main/scala/org/apache/spark/sql/hive/llap/LlapSessionCatalog.scala, src/test/scala/com/hortonworks/spark/sql/hive/llap/TestUtils.scala
Use DBCP2 for creating the connection pool for each user.
Post the test results here. 
```
spark.sql.hive.llap.dbcp2 initialSize:2 maxTotal:200 maxIdle:100 maxConnLifetimeMillis:4000 maxWaitMillis:2000    
[root@ctr-e134-1499953498516-70977-01-000007 python]# ./spark-ranger-secure-test.py TableTestSuite
.....................
Ran 21 tests in 3128.994s
spark.sql.hive.llap.dbcp2 initialSize:1 maxTotal:40 maxIdle:10 maxConnLifetimeMillis:5000 maxWaitMillis:2000
[root@ctr-e134-1499953498516-70977-01-000007 python]# ./spark-ranger-secure-test.py TableTestSuite
.....................
Ran 21 tests in 3168.360s
OK
=> [SPARK-LLAP-160] Consider connection pooling to reuse connections to HS2

src/main/scala/com/hortonworks/spark/sql/hive/llap/LlapRelation.scala, src/main/scala/org/apache/spark/sql/hive/llap/LlapSessionCatalog.scala
This estimated table size would be used for optimizing the join plan. If the estimated size is not big, the broadcast join will be used. Thus, this PR is used to get the estimated table size from metadata s.t. computing optimized joined plan.  
```
[root@ctr-e134-1499953498516-99573-01-000002 python]# ./spark-ranger-secure-test.py TableTestSuite
.....................
Ran 21 tests in 3011.014s
[root@ctr-e134-1499953498516-99573-01-000002 python]# ./spark-ranger-secure-test.py DbTestSuite
....
Ran 4 tests in 612.001s
=> [SPARK-LLAP-156] Support LlapRelation table size property

src/main/scala/com/hortonworks/spark/sql/hive/llap/LlapRelation.scala
For larger row counts, break up single parallelize() call into  multiple smaller parallelize() calls, and merge together to a single result using UnionRDD.
Tested manually on TPCDS cluster
=> spark-llap: count(*) fails when more than Int.MaxValue rows

build.sbt
This PR updates the dependency to use the latest HDP (2.6.4.0).
Pass Travis CI only.
=> [SPARK-LLAP-184] Use HDP 2.6.4.0 dependency

build.sbt, src/main/scala/org/apache/spark/sql/hive/llap/LlapExternalCatalog.scala, src/main/scala/org/apache/spark/sql/hive/llap/LlapSessionCatalog.scala
Recently, Apache Spark 2.3 is released offcially. This PR updates the dependency to Apache Spark 2.3.
Pass the Travis CI build test.
This closes #188 .
=> [SPARK-LLAP-188] Use Apache Spark 2.3

.travis.yml
This PR proposes to add `sbt test` to run the tests via Travis CI.
Seems we don't actually run the tests:
https://github.com/hortonworks-spark/spark-llap/blob/1683b3cc7bc107d44620af58292a37013c36e1c6/build.sbt#L149
This should be tested via Travis trigger.
Closes #196
=> [SPARK-LLAP-196] Explicitly run tests via Travis CI

src/main/scala/com/hortonworks/spark/sql/hive/llap/FilterPushdown.scala, src/test/scala/com/hortonworks/spark/sql/hive/llap/TestFilterPushdown.scala
This PR replaces `in` with empty values to `case when`. See also SPARK-18436.
Unit tests are added.
Closes #200
=> [SPARK-LLAP-200] Replace in with empty values to case when

build.sbt
Update versions in build.sbt and add Hive dependency for ParserUtils
Build succeeds.
The commit bootstraps a new code line.
Please ignore the test failures. It can't find Hive 3.0 in Maven Central, so we're having to resolve it from our local build for now.
=> Update version in build.sbt and add Hive dependency for ParserUtils

build.sbt, src/main/java/com/hortonworks/spark/sql/hive/llap/DriverResultSet.java, src/main/scala/com/hortonworks/spark/sql/hive/llap/HS2JDBCWrapper.scala
Produce HS2 ResultSets as DataFrames. Allows simple DDL like "show tables" to be 
executed by the Driver without any Executors.
This is needed because Spark won't talk to the Hive Metastore, so we need DDL to come through HS2.
Refactored a piece of code which was needed in two places into the method "populateSchemaFields"
manual tests on 19 node Hadoop cluster
=> [SPARK-LLAP-208] DataFrames from HS2 to Driver

build.sbt
Add jackson exclusion in 1 Tez and 1 Hive module dependency
Existing unit tests succeed
```
[info] ScalaTest
[info] Run completed in 8 seconds, 262 milliseconds.
[info] Total number of tests run: 25
[info] Suites: completed 4, aborted 0
[info] Tests: succeeded 25, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 25, Failed 0, Errors 0, Passed 25
[success] Total time: 39 s, completed May 6, 2018 8:11:43 PM
```
=> [SPARK-LLAP-209] Add jackson exclusions to fix SparkSession use in unit tests

src/main/java/com/hortonworks/spark/sql/hive/llap/CreateTableBuilder.java, src/main/java/com/hortonworks/spark/sql/hive/llap/DriverResultSet.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HWConf.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseBuilder.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseSession.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseSessionImpl.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseSessionState.java, src/main/java/com/hortonworks/spark/sql/hive/llap/util/HiveQlUtil.java, src/main/java/com/hortonworks/spark/sql/hive/llap/util/TriFunction.java, src/test/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseBuilderTest.java, src/test/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseSessionHiveQlTest.java, src/test/java/com/hortonworks/spark/sql/hive/llap/MockConnection.java, src/test/java/com/hortonworks/spark/sql/hive/llap/MockHiveWarehouseConnector.java, src/test/java/com/hortonworks/spark/sql/hive/llap/MockHiveWarehouseDataReader.java, src/test/java/com/hortonworks/spark/sql/hive/llap/MockHiveWarehouseDataReaderFactory.java, src/test/java/com/hortonworks/spark/sql/hive/llap/MockHiveWarehouseDataSourceReader.java, src/test/java/com/hortonworks/spark/sql/hive/llap/MockHiveWarehouseSessionImpl.java, src/test/scala/com/hortonworks/spark/sql/hive/llap/TestJavaProxy.scala
Add missing apache headers from previous PR. Change default hs2 port in HWConf to real hs2 default port.
Check that build still succeeds
=> [SPARK-LLAP-207] Add missing apache headers. Change default hs2 port.

build.sbt, src/main/java/com/hortonworks/spark/sql/hive/llap/CreateTableBuilder.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseSession.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseSessionImpl.java, src/main/scala/com/hortonworks/spark/sql/hive/llap/HS2JDBCWrapper.scala, src/test/java/com/hortonworks/spark/sql/hive/llap/MockHiveWarehouseSessionImpl.java
Add executeUpdate to API for raw sql create/update/delete/insert. 
Using the existing HiveWarehouseSession.execute(sql) will succeed in doing an update to Hive, but it will throw an exception to the client on JDBC close. "Caused by: java.sql.SQLException: The query did not generate a result set!"
Additionally, build began failing due to
```
[error] 1 error was encountered during merge
java.lang.RuntimeException: deduplicate: different file contents found in the following:
/Users/ewohlstadter/.ivy2/cache/org.apache.arrow/arrow-vector/jars/arrow-vector-0.8.0.jar:git.properties
/Users/ewohlstadter/.ivy2/cache/org.apache.arrow/arrow-format/jars/arrow-format-0.8.0.jar:git.properties
/Users/ewohlstadter/.ivy2/cache/org.apache.arrow/arrow-memory/jars/arrow-memory-0.8.0.jar:git.properties
``` …
=> [SPARK-LLAP-212] Add executeUpdate to HiveWarehouseSession API

src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseSession.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseSessionImpl.java
Remove exec which is a short name for execute API consistency.
Existing tests should cover this.
=> [SPARK-LLAP-214] Remove exec which is a short name for execute for API consistency

src/main/scala/com/hortonworks/spark/sql/hive/llap/HS2JDBCWrapper.scala, src/main/scala/com/hortonworks/spark/sql/hive/llap/LlapQueryExecutionListener.scala, src/test/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseBuilderTest.java, src/test/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseSessionHiveQlTest.java, src/test/scala/com/hortonworks/spark/sql/hive/llap/TestJavaProxy.scala, src/test/scala/com/hortonworks/spark/sql/hive/llap/TestLlapQueryExecutionListener.scala
This PR proposes to fix some tests to stop the spark session so that it adds the query execution listener once.
Tests were fixed.
Closes #216
=> [SPARK-LLAP-216] Fix test cases to stop sessions to ensure listener is not added multiple times

src/main/scala/com/hortonworks/spark/sql/hive/llap/HS2JDBCWrapper.scala
Don't log the warnings from DBCP2 about expired connections
```
scala> hive.dropTable(tempTable, true, false)
```
was consistently triggering the warning to be logged on the console. 
After making the change, I don't see it anymore.
=> [SPARK-LLAP-218] Don't log expired connections

.gitignore, .travis.yml, python/pyspark_llap/__init__.py, python/pyspark_llap/sql/__init__.py, python/pyspark_llap/sql/session.py, python/pyspark_llap/sql/tests.py, python/setup.py, src/main/java/com/hortonworks/spark/sql/hive/llap/DriverResultSet.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HWConf.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseBuilder.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseSessionImpl.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseSessionState.java, src/test/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseSessionHiveQlTest.java, src/test/java/com/hortonworks/spark/sql/hive/llap/MockConnection.java, src/test/java/com/hortonworks/spark/sql/hive/llap/MockHiveWarehouseDataReader.java, src/test/java/com/hortonworks/spark/sql/hive/llap/MockHiveWarehouseSessionImpl.java, src/test/scala/com/hortonworks/spark/sql/hive/llap/TestJavaProxy.scala
This PR adds the testing environment to Travis and the Python version of HiveWarehouseSession.
Manually tested and unit tests were added. The tests are basically the conversion of `HiveWarehouseBuilderTest` and `HiveWarehouseSessionHiveQlTest` at Java side.
Travis setting and Python setting was added to enable Python tests.
Manually tested with Python 3 and PyPy too.
Closes #221
=> [SPARK-LLAP-221] Add Python testing environment to Travis and  Python version of HiveWarehouseSession

.travis.yml, build.sbt
This PR produces a zipped Python library like PySpark. It's source zip; therefore, it should support other Python versions universally.
Travis CI tests.
Closes #223
=> [SPARK-LLAP-223] Produces a zipped module for Python APIs of HiveWarehouseSession

src/main/scala/com/hortonworks/spark/sql/hive/llap/HS2JDBCWrapper.scala
Order should be (userProvidedDriverClass, url, userName, dbcp2Configs)
Fix getConnector helper method which derives arguments from HWConf class.
Uncommitted integration test:
```
val hive = com.hortonworks.spark.sql.hive.llap.HiveWarehouseBuilder.session(spark).build()
hive.setDatabase("tpcds_bin_partitioned_orc_1000")
val df = hive.executeQuery("select * from web_sales")
hive.setDatabase("spark_llap")
val tempTable = "t_" + System.currentTimeMillis()
hive.createTable(tempTable).ifNotExists().column("ws_sold_time_sk", "bigint").column("ws_ship_date_sk", "bigint").create()
df.select("ws_sold_time_sk", "ws_ship_date_sk").filter("ws_sold_time_sk > 80000").write.format("com.hortonworks.spark.sql.hive.llap.HiveWarehouseConnector").option("table", tempTable).save()
val df2 = …
```
=> Passed in wrong arguments for new getConnector helper method. 

python/pyspark_llap/sql/tests.py, src/main/java/com/hortonworks/spark/sql/hive/llap/HWConf.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseBuilder.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseSession.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseSessionImpl.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseSessionState.java, src/main/java/com/hortonworks/spark/sql/hive/llap/util/HiveQlUtil.java, src/main/scala/com/hortonworks/spark/sql/hive/llap/HS2JDBCWrapper.scala, src/test/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseBuilderTest.java, src/test/java/com/hortonworks/spark/sql/hive/llap/MockHiveWarehouseConnector.java
Previous code had some loopholes where configuration wasn't available to DataSourceWriter. 
The DataSourceWriter code hasn't been merged yet, so this PR is in preparation for that.
Also added a fix for the arguments to HiveQl.dropDatabase in this PR.
Modified existing UT.
=> [SPARK-LLAP-227] Fixup configuration classes. 

python/pyspark_llap/sql/session.py, python/pyspark_llap/sql/tests.py, src/main/java/com/hortonworks/spark/sql/hive/llap/HWConf.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseBuilder.java, src/main/scala/com/hortonworks/spark/sql/hive/llap/HS2JDBCWrapper.scala, src/test/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseBuilderTest.java, src/test/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseSessionHiveQlTest.java, src/test/java/com/hortonworks/spark/sql/hive/llap/SessionTestBase.java, src/test/java/com/hortonworks/spark/sql/hive/llap/TestSecureHS2Url.java, src/test/scala/com/hortonworks/spark/sql/hive/llap/TestJavaProxy.scala
Resolve HS2URL using: `spark.security.credentials.hiveserver2.enabled`, `spark.sql.hive.hiveserver2.jdbc.url.principal`, and `spark.sql.hive.hiveserver2.jdbc.url`
Add "principal" and "credentialsEnabled" helper to HiveWarehouseBuilder
Refactored some test code
Added UT.
Manually smoke tested the 3 security modes on kerberized and non-kerberized cluster.
Manually smoke tested kerberized authentication to Ranger is working.
=> SPARK-LLAP-235: Add kerberos support for HS2 url. Refactor SparkSession setup/tearDown into test base class

build.sbt, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseConnector.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseDataSourceWriter.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseDataWriter.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseDataWriterFactory.java, src/main/java/com/hortonworks/spark/sql/hive/llap/SimpleWriterCommitMessage.java, src/main/java/com/hortonworks/spark/sql/hive/llap/util/HiveQlUtil.java, src/test/java/com/hortonworks/spark/sql/hive/llap/MockHiveWarehouseConnector.java, src/test/java/com/hortonworks/spark/sql/hive/llap/MockHiveWarehouseSessionImpl.java, src/test/java/com/hortonworks/spark/sql/hive/llap/MockWriteSupport.java, src/test/java/com/hortonworks/spark/sql/hive/llap/TestWriteSupport.java, src/test/scala/com/hortonworks/spark/sql/hive/llap/TestJavaProxy.scala
Add batch WriteSupport:
1. Write DataFrame to ORC temp dir
2. Use HS2 to "LOAD DATA INPATH" from ORC files to target table
3. Delete temp dir
UT
=> Add batch WriteSupport

src/main/java/com/hortonworks/spark/sql/hive/llap/CountDataReader.java, src/main/java/com/hortonworks/spark/sql/hive/llap/CountDataReaderFactory.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HWConf.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveWarehouseDataSourceReader.java, src/test/java/com/hortonworks/spark/sql/hive/llap/MockHiveWarehouseConnector.java, src/test/java/com/hortonworks/spark/sql/hive/llap/TestReadSupport.java, src/test/scala/com/hortonworks/spark/sql/hive/llap/TestJavaProxy.scala
Migrate the logic from master branch that specially handles `.count()` action.
Instead of using parallelize, when the count value from HS2 is `X`:
1. Launch `COUNT_TASKS` num of tasks (configurable)
2. `(COUNT_TASKS - 1)` tasks generate `X/(COUNT_TASKS - 1)` rows.
3. 1 task generates `X % (COUNT_TASKS - 1)` rows
UT
=> Add count support for branch-2.3-3.0

.travis.yml, build.sbt
This bumps Apache Spark version to 2.3.1.
Like before, `branch-2.3-3.0` build will fail.
This closes #248 .
=> [SPARK-LLAP-248] Use Apache Spark 2.3.1 and Hadoop 3.1
