hortonworks-spark/spark-llap

README.md
=> [SPARK-LLAP-3] Use Apache Trade Mark explicitly.

.travis.yml, README.md, build.sbt
=> [SPARK-LLAP-5] Add Travis CI for `branch-2.0`

src/main/scala/org/apache/spark/sql/hive/llap/LlapExternalCatalog.scala
Currently, `Spark-LLAP` always creates tables without considering Ranger access rule while Hive does not.
**SPARK-LLAP**
```sql
$ beeline -u jdbc:hive2://localhost:10016 -n spark -e 'create table t(a int)'
...
+---------+--+
| Result  |
+---------+--+
+---------+--+
No rows selected (0.707 seconds)
Beeline version 1.2.1000.2.5.3.0-37 by Apache Hive
Closing: 0: jdbc:hive2://localhost:10016
```
**HIVE**
```sql
$ beeline -u jdbc:hive2://localhost:10500 -n spark -e 'create table t(a int)'
...
Error: Error while compiling statement: FAILED: HiveAccessControlException Permission denied: user [spark] does not have [CREATE] privilege on [default/t] (state=42000,code=40000)
Closing: 0: jdbc:hive2://localhost:10500
```
This closes #12.
=> [SPARK-LLAP-12] `CREATE TABLE` should be blocked properly according to the access rule

src/main/scala/org/apache/spark/sql/hive/llap/LlapSessionCatalog.scala
Currently, spark-llap always show columns for a visible table. It should be blocked in case of no permission on `*`.
```bash
$ beeline -u jdbc:hive2://localhost:10016 -n spark -e "DESC employee"
+------------------+----------------+----------+--+
|     col_name     |   data_type    | comment  |
+------------------+----------------+----------+--+
| employee_id      | int            | NULL     |
...
+------------------+----------------+----------+--+
```
This closes #17
=> [SPARK-LLAP-17] `DESC` should be blocked properly according to the access rule

src/main/scala/org/apache/spark/sql/hive/llap/LlapExternalCatalog.scala
Currently, `ALTER TABLE ... DROP PARTITION` fails with the following errors when the user doesn't have a enough HDFS privilege to change `hive` warehouse directory. When Spark Thrift Server is running as `hive`, this is not a problem. Also, this is not about permission issue. After correct authorization, this situation happens.
```
[alter_drop_partiton_3_t_alter] dongjoon ALTER TABLE t_alter_part DROP PARTITION (c=1)
Error: org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: Got exception: java.io.IOException Failed to move to trash:
hdfs://.../apps/hive/warehouse/spark_ranger_test.db/t_alter_part/c=1; (state=,code=0)
```
For example, run Spark Thrift Server in a normal user account without `HDFS` privilege, and
execute `ALTER TABLE ... DROP …
=> [SPARK-LLAP-30] `DROP PARTITION` should work without HDFS privilege

README.md
This PR updates `README.md`.
This closes #34.
=> [SPARK-LLAP-34] Update README.md

README.md
This PR adds a section about `use cases` to give more clear example.
N/A
=> Add use cases

build.sbt
This PR updates the metadata of generated `pom.xml` in Maven repository.
- Add license
- Add project url
- Remove repositories from pom
N/A
This closes #53 .
=> [SPARK-LLAP-53] Update pom metadata

build.sbt
This PR aims to bump the version number into 1.0.5-2.1.
N/A
=> [SPARK-LLAP-57] Bump to 1.0.5-2.1 and publish.

assembly/pom.xml
This PR adds a maven project to publish `spark-llap-assembly_2.11` artifact.
N/A
This closes #61 .
=> [SPARK-LLAP-61] Add `assembly` project

src/main/scala/org/apache/spark/sql/hive/llap/LlapContext.scala
The followings are supported.
- CREATE DATABASE
- DROP DATABASE
- SHOW DATABASES
- CREATE TABLE
- DROP TABLE
- ALTER TABLE
N/A
This closes #71 .
=> [SPARK-LLAP-71] Fix branch-1.6 with the known issues found in branch-2.1

build.sbt
This PR bumps to 1.0.3-1.6 to publish.
N/A
This closes #74 .
=> [SPARK-LLAP-74] Bump to 1.0.3-1.6 and publish

assembly/pom.xml, build.sbt
This PR bumps the version to 1.0.4-1.6.
N/A
=> [SPARK-LLAP-80] Bump to 1.0.4-1.6

src/test/python/spark-ranger-secure-test.py, src/test/python/spark-ranger-test.py
For convenience, this PR fixes test scripts to support Python 2.6. We don't need to install python2.7 for some OS.
N/A
=> [SPARK-LLAP-83] Test script should work with Python2.6

README.md
This PR adds the build status into `README.md`.
N/A
=> [SPARK-LLAP-90] Add Travis CI build status

.travis.yml, README.md
This adds Travis CI.
Pass the Travis CI.
=> [SPARK-LLAP-93] Add Travis CI for branch-1.6

src/main/scala/org/apache/spark/sql/hive/llap/LlapSessionState.scala
To support kerberized YARN cluster mode using delegation token, this PR simplifies the existing configurations and adds new configurations. Note that this is an incompatible change.
**BEFORE**
- spark.sql.hive.hiveserver2.url
**AFTER**
- spark.sql.hive.hiveserver2.jdbc.url
- spark.sql.hive.hiveserver2.jdbc.url.principal
- spark.yarn.security.credentials.hiveserver2.enabled
Pass the test suite with new configurations.
=> [SPARK-LLAP-96] Refactor and add configurations to support kerberized YARN cluster mode

src/main/scala/org/apache/spark/sql/hive/llap/LlapExternalCatalog.scala
This PR refactors `LlapExternalCatalog` to use `tryWithResource` consistently.
Pass the test suite.
```bash
$ python spark-ranger-test.py
.......................
Ran 23 tests in 2359.363s
OK
```
=> [SPARK-LLAP-98] Refactor `LlapExternalCatalog` to use `tryWithResource`

assembly/pom.xml, build.sbt
This updates the dependencies to use the latest versions.
For Apache Spark dependencies, it will be updated again after official Apache Spark 2.1.1 release.
N/A
This closes #100 .
=> [SPARK-LLAP-100] Update dependencies to use the latest versions.

patch/0001-SPARK-LLAP-RANGER-Integration_2.1.0.patch, patch/0001-SPARK-LLAP-RANGER-Integration_2.1.1.patch
This adds HiveServer2CredentialProvider to the patches.
N/A
This closes #102
=> [SPARK-LLAP-102] Add HiveServer2CredentialProvider

src/main/scala/org/apache/spark/sql/hive/llap/LlapMetastoreCatalog.scala
Currently, Spark-LLAP 2.1 fails to handle table alias. This fixes the bug and simplify the logic.
Tested manually.
This closes #106
=> [SPARK-LLAP-106] Fix table alias bug

assembly/pom.xml, build.sbt
This PR bumps the versions to v1.1.1-21 and do publish. This PR requires the followings.
- Both #105 and #107 should be merged before this PR.
- Backport both commits from `master` branch to `branch-2.1` branch.
- Make a tag on branch-2.1 and publich via Jenkins.
This closes #108 .
=> [SPARK-LLAP-108] Bump to v1.1.1-2.1 and publish

build.sbt
=> [DEPLOY-100] Use the Internal Hadoop

src/main/scala/com/hortonworks/spark/sql/hive/llap/LlapRelation.scala
=> [Bug-64676][Branch-1.6] Should close/reuse connections in spark-llap

src/main/scala/com/hortonworks/spark/sql/hive/llap/LlapRelation.scala, src/main/scala/org/apache/spark/sql/hive/llap/DefaultSource.scala
=> [BUG-64676] Create and close the connection explictitly

src/main/scala/com/hortonworks/spark/sql/hive/llap/HS2JDBCWrapper.scala, src/main/scala/com/hortonworks/spark/sql/hive/llap/RowConverter.scala
Support complex types, using the changes in HIVE-16568 to support complex types in the LLAP input format.
N/A
=> [SPARK-LLAP-114] Support for complex types, using HIVE-16568

src/main/scala/org/apache/spark/sql/hive/llap/LlapContext.scala
add access control for listing tables. 
test manually on the cluster
=> [SPARK-LLAP-127] Table information will under access control 

assembly/pom.xml, build.sbt
This PR bumps the version to snapshot.
Pass Travis CI.
=> [SPARK-LLAP-140] Bump to v1.1.3-2.1-SNAPSHOT

build.sbt, src/main/scala/com/hortonworks/spark/sql/hive/llap/HS2JDBCWrapper.scala, src/main/scala/com/hortonworks/spark/sql/hive/llap/RowConverter.scala
This bumps the Hive dependency to HDP 2.6.1.0 for Spark-LLAP branch-1.6.
Fix the scala style issue.
no test, and build passed.
=> [SPARK-LLAP-135][BRANCH-1.6] Bump to HDP 2.6.1

build.sbt, project/plugins.sbt
reduce dependency as the branch 2.1
I manually verify the dependence list
=> [SPARK-LLAP-125][BRANCH-1.6] Reduce the number of included artifacts

build.sbt
change the sbt for the hadoop yarn
manual tests in 2.6.3.0-60
=> [SPARK-LLAP-148] NoClassDefFoundError: org/apache/hadoop/registry/client/binding/RegistryUtils #151

project/plugins.sbt, src/main/scala/com/hortonworks/spark/sql/hive/llap/HS2JDBCWrapper.scala, src/main/scala/com/hortonworks/spark/sql/hive/llap/RowConverter.scala, src/test/scala/org/apache/spark/sql/hive/llap/TestUtils.scala
This fixes the scalastyle in branch-1.6.
Pass the Travis CI.
=> [SPARK-LLAP-154] Fix scalastyle in branch-1.6.

build.sbt, src/main/scala/com/hortonworks/spark/sql/hive/llap/HS2JDBCWrapper.scala, src/main/scala/com/hortonworks/spark/sql/hive/llap/LlapRelation.scala, src/main/scala/org/apache/spark/sql/hive/llap/DefaultSource.scala, src/main/scala/org/apache/spark/sql/hive/llap/LlapExternalCatalog.scala, src/main/scala/org/apache/spark/sql/hive/llap/LlapSessionCatalog.scala, src/test/scala/com/hortonworks/spark/sql/hive/llap/TestUtils.scala
Reverts hortonworks-spark/spark-llap#164
=> Revert "[SPARK-LLAP-160] Consider connection pooling to reuse connections to HS2"

src/main/scala/com/hortonworks/spark/sql/hive/llap/LlapRelation.scala
According to [HIVE-17873](https://issues.apache.org/jira/browse/HIVE-17873), we will reduce Handle Id.
=> Remove call to close() at the start of LlapRelation.buildScan()

src/main/scala/com/hortonworks/spark/sql/hive/llap/RowConverter.scala
This is 4 lines addition ( [diff](https://github.com/hortonworks-spark/spark-llap/pull/182/files?w=1) )
```scala
+    if (value == null) {
+      null
+    } else {
... previous code ...
+      }
```
=> Fix null handling of complex types

src/main/scala/org/apache/spark/sql/hive/llap/LlapExternalCatalog.scala, src/main/scala/org/apache/spark/sql/hive/llap/LlapSessionCatalog.scala
=> Fix table stats for LlapRelation on branch-2.2

src/main/scala/com/hortonworks/spark/sql/hive/llap/RowConverter.scala
When profiling in Spark side with 550M records processing, row conversions took CPU times. This is due to scala type conversions. It would be good to consider using regular iterator which would be less CPU intensive.
=> Use iterator instead of scala conversions in RowConverter

build.sbt, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveStreamingDataSource.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveStreamingDataSourceWriter.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveStreamingDataWriter.java, src/main/java/com/hortonworks/spark/sql/hive/llap/HiveStreamingDataWriterFactory.java, src/main/java/com/hortonworks/spark/sql/hive/llap/SimpleWriterCommitMessage.java, src/main/java/com/hortonworks/spark/sql/hive/llap/streaming/HiveStreamingDataSource.java, src/main/java/com/hortonworks/spark/sql/hive/llap/streaming/HiveStreamingDataSourceWriter.java, src/main/scala/com/hortonworks/spark/hive/utils/HiveIsolatedClassLoader.scala, src/test/scala/com/hortonworks/spark/sql/hive/streaming/TestHiveStreaming.scala
Fixed merge conflicts on PR that had been based on diverged branch `datav2`.
`TestHiveStreaming ` example in patch.
=> Fix merge conflicts from Streaming Support PR on branch datav2

README.md
=> SPARK-LLAP-246: Updating README for branch-2.3-3.0

README.md
=> SPARK-LLAP-251, update compatibility notes
